# Generated by Django 3.0.5 on 2020-04-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chair', models.IntegerField(default=2)),
                ('esprit', models.IntegerField(default=2)),
                ('essence', models.IntegerField(default=2)),
                ('point_de_vie', models.IntegerField(default=4)),
                ('point_de_focus', models.IntegerField(default=4)),
                ('point_de_pouvoir', models.IntegerField(default=4)),
                ('dettes', models.IntegerField(default=0)),
            ],
        ),
    ]
