# Generated by Django 3.0.5 on 2020-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applsr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arcanes',
            field=models.IntegerField(default=3),
        ),
    ]
