# Generated by Django 3.0.5 on 2020-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applsr', '0002_character_arcanes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.CharField(default='aucun', max_length=255),
        ),
    ]
