# Generated by Django 3.0.5 on 2020-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applsr', '0003_character_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arcanes_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='character',
            name='point_de_focus_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='character',
            name='point_de_pouvoir_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='character',
            name='point_de_vie_max',
            field=models.IntegerField(default=4),
        ),
    ]
