# Generated by Django 3.0.5 on 2020-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applsr', '0004_auto_20200403_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('dices', models.CharField(max_length=255)),
            ],
        ),
    ]
