# Generated by Django 3.0.5 on 2020-04-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applsr', '0005_diceroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fl',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='fs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='fu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='lancer',
            field=models.CharField(default='no one', max_length=255),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
