# Generated by Django 3.0.5 on 2020-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applsr', '0006_auto_20200421_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MasterwordGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1c1', models.CharField(max_length=255)),
                ('l1c2', models.CharField(max_length=255)),
                ('l1c3', models.CharField(max_length=255)),
                ('l2c1', models.CharField(max_length=255)),
                ('l2c2', models.CharField(max_length=255)),
                ('l2c3', models.CharField(max_length=255)),
                ('l3c1', models.CharField(max_length=255)),
                ('l3c2', models.CharField(max_length=255)),
                ('l3c3', models.CharField(max_length=255)),
                ('l4c1', models.CharField(max_length=255)),
                ('l4c2', models.CharField(max_length=255)),
                ('l4c3', models.CharField(max_length=255)),
                ('l5c1', models.CharField(max_length=255)),
                ('l5c2', models.CharField(max_length=255)),
                ('l5c3', models.CharField(max_length=255)),
                ('l6c1', models.CharField(max_length=255)),
                ('l6c2', models.CharField(max_length=255)),
                ('l6c3', models.CharField(max_length=255)),
                ('l7c1', models.CharField(max_length=255)),
                ('l7c2', models.CharField(max_length=255)),
                ('l7c3', models.CharField(max_length=255)),
                ('indice', models.CharField(max_length=255)),
                ('prop1', models.CharField(max_length=255)),
                ('prop2', models.CharField(max_length=255)),
                ('prop3', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('valide1', models.BooleanField(default=False)),
                ('valide2', models.BooleanField(default=False)),
                ('valide3', models.BooleanField(default=False)),
                ('valide4', models.BooleanField(default=False)),
                ('valide5', models.BooleanField(default=False)),
                ('valide6', models.BooleanField(default=False)),
                ('valide7', models.BooleanField(default=False)),
                ('valide8', models.BooleanField(default=False)),
            ],
        ),
    ]
