# Generated by Django 3.0.5 on 2020-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applsr', '0007_masterword_masterwordgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('charisme', models.IntegerField(default=2)),
                ('combat', models.IntegerField(default=2)),
                ('magie', models.IntegerField(default=2)),
                ('savoir', models.IntegerField(default=2)),
                ('navigation', models.IntegerField(default=2)),
                ('nature', models.IntegerField(default=2)),
                ('point_de_vie', models.IntegerField(default=4)),
                ('point_de_vie_max', models.IntegerField(default=4)),
                ('point_de_pouvoir', models.IntegerField(default=4)),
                ('point_de_pouvoir_max', models.IntegerField(default=4)),
            ],
        ),
        migrations.DeleteModel(
            name='MasterwordGame',
        ),
    ]
