# Generated by Django 3.0.5 on 2020-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applsr', '0010_remove_viking_point_de_pouvoir_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='viking',
            name='joueur',
            field=models.CharField(default='personne', max_length=255),
        ),
    ]
